### ISSUE TITLE
Support Grouping

### ISSUE THREAD

**Issue by naqaden** [halsafar/TaskBarAppIdAdjuster#1]
It's noted as currently unsupported in the readme, but I'd love to see this project finished as a workaround for auto-grouping rogue apps with their pin's AppID.

**Comment by halsafar** [comment]
Essentially the opposite of ungroup.  When a rule is matched it will group them instead of ungrouping.  Assuming that fits your use case I am happy to implement this.

**Comment by naqaden** [comment]
Exactly. That would be great, thank you!

**Comment by halsafar** [comment]
So to my surprise this does seem to be already implemented.  Looks like the README is out of date.  

Can you confirm on your side if it is working?  If not please let me know the name of the executable you are working with so I can do some testing.  Thanks!

**Comment by naqaden** [comment]
I tried it out. Here's my simple test config.json (added WordPad and set both actions to 1):
```
{
    "ApplicationsToRandomize": [
        {
            "Name": "notepad",
            "Action": 1
        },
        {
            "Name": "wordpad",
            "Action": 1
        }
    ]
}
```
The result was each AppID got renamed to **tbAdjusterGroup_NAME** (where NAME is whatever process name given in the config), causing them both to shift to the right end of the taskbar. But since they got different AppIDs, they weren't actually grouped. They don't stick together when dragged around the taskbar.

Have I set up the config correctly if the goal is to group Notepad with WordPad?

**Comment by halsafar** [comment]
Okay I understand better what you are asking.  To implement this I will need to change the structure of the settings file a bit.

Something like this:

```
{
    "ApplicationsToRandomize": [
        {
            "Name": "SomeUniqueNameForThisRule",
            "Match": ["notepad", "wordpad"],
            "Action": 1
        },
    ]
}
```

Basically we need to know which apps you want to group in a single rule rather than split across both.

I'll get this implemented for you.

**Comment by halsafar** [comment]
Hey @naqaden I pushed support for this into the branch 'support-grouping'.  I tested your wordpad + notepad setup (similar to my example config above) and it now works as expected.  There is a bit of clean up left to do before I cut a release. 

I'd like to verify this on your end.  Are you able to test from source or would you like me to cut a test build for you?

**Comment by naqaden** [comment]
A test build would be great. I'm not set up to build atm. Thanks!

**Comment by halsafar** [comment]
Release cut, sorry for the delay.  Life has been very busy.  Let me know how it goes.
https://github.com/halsafar/TaskBarAppIdAdjuster/releases/tag/1.0-rc1

**Comment by naqaden** [comment]
No worries! Thanks for the build.

I just tried it out with this config, worked like a charm:
```
{
    "ApplicationsToRandomize": [
        {
            "Name": "editors",
            "Rules": ["notepad", "wordpad"],
            "Action": 1
        },
    ]
}
```

**Comment by halsafar** [comment]
Awesome!  Glad to hear. I'll close this ticket out.  Thanks for the feature request. Always fun.
